### ISSUE TITLE
Sticker - 사진 자르기 오류 

### ISSUE THREAD

**Issue by Artsyork** [yapp-90s/90s_iOS_V1_Deprecated#1]
시물레이터에서 정상 작동, 기기에서는 오작동

**Comment by KakaoTocs** [comment]
Image 크롭시 설정한 크기/위치와 다르게  크롭 되는 이유는
Image 크롭시 cropToRect메소드를 이용하는데, 이때 내부 Logic에서 scale 값을 이용하는데, scale값이 정확하지 않음

scale값은 초기 ImageCropVC viewDIdLoad에서 image를 넣어줄때 scale값을 계산해서 직접 넣어 줘야 하는데, 넣어주는 Logic이 없음
![image](https://user-images.githubusercontent.com/22838614/91653335-c4939d80-eada-11ea-8ef8-315ede1ab0e1.png)
![image](https://user-images.githubusercontent.com/22838614/91653348-d9703100-eada-11ea-8d96-c6f7920abf68.png)

**Comment by KakaoTocs** [comment]
scale값을 먼저 계산해서 Rect값을 넣어 주도록 수정했고, 이미지 사이즈가 조금 다른거는 crop  테두리 두깨 떄문인걸로 추측
![image](https://user-images.githubusercontent.com/22838614/91653624-66b48500-eadd-11ea-9802-f8efe65f4272.png)
![image](https://user-images.githubusercontent.com/22838614/91653627-6e742980-eadd-11ea-9332-98029833288c.png)
![image](https://user-images.githubusercontent.com/22838614/91653621-5f8d7700-eadd-11ea-946a-633ee1d1157c.png)
