### ISSUE TITLE
Sign - 회원가입 이용약관 내용 없음

### ISSUE THREAD

**Issue by Artsyork** [yapp-90s/90s_iOS_V1_Deprecated#16]

**Comment by Richardlee-korea** [comment]
슬랙으로 주시면 더 빠른 답변 가능하답니당!

기존에 제작했던게 없나요? 없으시다면 어플이 많이 변경되었다 들었는데(결제가 빠짐 등) 간단한 IA와 어플 변경사항을 정리해서 저한테 알려주실 분이 있으신가요ㅠㅠㅠ 있으셔야 제가 업무진행이 가능할 것 같습니다!

**Comment by Artsyork** [comment]
토요일까지 전달해드릴게요!

**Comment by Artsyork** [comment]
기획서에 추가 완료
